export const SCENE_KEYS = Object.freeze({
  PRELOAD_SCENE: 'PRELOAD_SCENE',
  BATTLE_SCENE: 'BATTLE_SCENE',
  WORLD_SCENE: 'WORLD_SCENE',
  TITLE_SCENE: 'TITLE_SCENE',
  OPTIONS_SCENE: 'OPTIONS_SCENE',
  TEST_SCENE: 'TEST_SCENE',
});
